### PR TITLE
Removing dependency to sleep

### PR DESCRIPTION
**Pull request by lpalbou**
This library was introduced for testing but is no longer (or has never been used).

It currently prevents building on several OS and is causing issues for automated deployment, including within the Alliance.

### CODE REVIEW

**Comment by lpalbou** [comment]
Once merged, the new NPM version of the library needs to be published

**Comment by lpalbou** [comment]
@kltm

**Comment by kltm** [comment]
Okay, I now recall what's going on here. The library is indeed used when doing tests (in a node environment). The reason it's there is to give the internal testing server a chance to spin up to bounce tests off of. This was effective, but the tests seem to be in a bit of a state at this point anyways, so there is no harm in taking this PR and circling around to fix up the tests later on.

**Comment by kltm** [comment]
@lpalbou 
```
+ bbop-rest-manager@0.0.18
```

**Comment by lpalbou** [comment]
Great, thanks.

Turns out bbop-manager-minerva uses a specific version of bbop-rest-manager and not the latest, so the other package.json have to be updated: https://github.com/berkeleybop/bbop-manager-minerva/pull/7

Note: this was using version 0.10, so this is far behind the current NPM releases and this may or may not have caused issues for the GO deployments.

**Pull request merged**
